import type { LocaleTemplates } from './types.js';

/** Arabic notification templates (HR portal Prompt 8) — the same keys as `en`. Numbers next to nouns use "label: value" forms to avoid agreement errors. */
export const ar: LocaleTemplates = {
  locale: 'ar',
  dir: 'rtl',
  formats: { date: 'd MMMM yyyy', dateTime: 'd MMMM yyyy، HH:mm', time: 'HH:mm' },
  separators: { parts: ' · ', list: '، ', range: ' إلى ' },
  common: {
    brand: 'FlowZa Time',
    footer: 'تصلك هذه الرسالة لأنك عضو في {{org}} على FlowZa Time.',
    footerPreferences: 'اختر الرسائل التي تصلك من إعدادات الإشعارات.',
    footerLocked: 'لا يمكن إيقاف هذا الإشعار.',
    preferencesLink: 'إعدادات الإشعارات',
    linkFallback: 'إن لم يعمل الزر، افتح هذا الرابط:',
    approve: 'موافقة',
    reject: 'رفض',
    oneClickHeading: 'أو اتخذ القرار من هذه الرسالة:',
    oneClickNote: 'سيُطلب منك التأكيد في FlowZa Time قبل تسجيل أي قرار. يعمل كل رابط مرة واحدة وتنتهي صلاحيته خلال 7 أيام. إن لم تكن تتوقع هذه الرسالة فتجاهلها.',
    level: 'المستوى {{stepNo}}',
    autoDeductNote: 'طُبّق الأثر على الراتب وفق سياسة الحضور',
    selfieKind: { in: 'تسجيل الحضور', out: 'تسجيل الانصراف' },
    punchKind: { in: 'تسجيل الحضور', out: 'تسجيل الانصراف' },
    financeDirection: { pull: 'مزامنة السحب', push: 'مزامنة الإرسال', sync: 'المزامنة' },
    payEffect: { half: 'نصف يوم', one: 'يوم واحد', other: '{{n}} يوم' },
  },
  plurals: {
    days: { zero: 'لا أيام', one: 'يوم واحد', two: 'يومان', few: '{{n}} أيام', many: '{{n}} يومًا', other: '{{n}} يوم' },
    attendanceDays: { zero: 'لا أيام', one: 'يوم واحد', two: 'يومان', few: '{{n}} أيام', many: '{{n}} يومًا', other: '{{n}} يوم' },
    hours: { zero: 'أقل من ساعة', one: 'ساعة واحدة', two: 'ساعتين', few: '{{n}} ساعات', many: '{{n}} ساعة', other: '{{n}} ساعة' },
    approvals: { zero: 'لا طلبات', one: 'طلب موافقة واحد', two: 'طلبا موافقة', few: '{{n}} طلبات موافقة', many: '{{n}} طلب موافقة', other: '{{n}} طلب موافقة' },
    balances: { zero: 'لا أرصدة', one: 'رصيد واحد', two: 'رصيدان', few: '{{n}} أرصدة', many: '{{n}} رصيدًا', other: '{{n}} رصيد' },
    punches: { zero: 'لا بصمات', one: 'بصمة واحدة', two: 'بصمتان', few: '{{n}} بصمات', many: '{{n}} بصمة', other: '{{n}} بصمة' },
  },
  entities: {
    ATTENDANCE_CORRECTION: 'تصحيح حضور', LEAVE: 'طلب إجازة', OVERTIME: 'عمل إضافي', MISSING_PUNCH: 'بصمة مفقودة', SHIFT_CHANGE: 'تغيير مناوبة',
    MANUAL_ATTENDANCE: 'حضور يدوي', ATTENDANCE_NOTE: 'سبب حضور', SHIFT_SWAP: 'تبديل مناوبة', COMP_OFF: 'إجازة تعويضية', REGULARISATION: 'تسوية حضور', OVERTIME_CLAIM: 'مطالبة عمل إضافي',
  },
  reportTypes: {
    daily_attendance: 'الحضور اليومي', monthly_attendance: 'الحضور الشهري', employee_attendance: 'حضور الموظف', branch_attendance: 'حضور الفرع',
    department_attendance: 'حضور القسم', late_report: 'التأخير', absence_report: 'الغياب', overtime_report: 'العمل الإضافي', missing_punch_report: 'البصمات المفقودة',
    device_sync_report: 'مزامنة الأجهزة', device_health_report: 'حالة الأجهزة', audit_report: 'التدقيق', payroll_summary: 'ملخص الرواتب', employee_directory: 'دليل الموظفين',
    leave_report: 'الإجازات', attendance_summary: 'ملخص الحضور', weekly_attendance: 'الحضور الأسبوعي', weekly_in_out: 'الدخول والخروج الأسبوعي', monthly_summary: 'ملخص الحضور الشهري', monthly_detail: 'تفاصيل الحضور الشهري',
  },
  syncJobTypes: {
    PULL_ATTENDANCE: 'سحب الحضور', PULL_EMPLOYEES: 'سحب الموظفين', PUSH_EMPLOYEE: 'إرسال موظف', PUSH_EMPLOYEES: 'إرسال الموظفين', DEVICE_HEALTH_CHECK: 'فحص حالة الجهاز',
    RECONCILIATION: 'المطابقة', TEST_CONNECTION: 'اختبار الاتصال', DELETE_EMPLOYEE: 'حذف موظف', RESTART_DEVICE: 'إعادة تشغيل الجهاز', PUSH_ATTENDANCE: 'إرسال الحضور',
  },
  geofenceReasons: {
    outside: 'خارج نطاق العمل', mock_location: 'تم اكتشاف موقع وهمي', location_missing: 'لم تتم مشاركة الموقع', gps_accuracy_too_low: 'دقة الموقع منخفضة',
    out_of_window: 'خارج الساعات المسموح بها', no_fences_assigned: 'لا يوجد نطاق عمل محدد', geofence_off: 'التحقق من نطاق العمل متوقف', inside: 'داخل نطاق العمل',
  },
  regularisationTypes: { missed_punch: 'بصمة فائتة', wrong_punch: 'بصمة خاطئة', wfh_unmarked: 'عمل من المنزل غير مسجّل', system_downtime: 'تعطّل النظام' },
  metrics: { employees: 'الموظفون', devices: 'الأجهزة', branches: 'الفروع', users: 'المستخدمون', storage_mb: 'التخزين', api_calls_month: 'استدعاءات الواجهة البرمجية' },
  financeErrors: {
    AUTH_FAILED: 'رُفضت بيانات الاعتماد', DEVICE_OFFLINE: 'تعذّر الوصول', RATE_LIMITED: 'تجاوز حد الطلبات', TIMEOUT: 'انتهت المهلة', UNSUPPORTED: 'غير مدعوم', NOT_FOUND: 'غير موجود',
    INVALID_CONFIG: 'مشكلة في الإعدادات', VENDOR_ERROR: 'خطأ من Finance', NOT_IMPLEMENTED: 'غير متاح', PROTOCOL_ERROR: 'رد غير مقروء', CONFLICT: 'تعارض', INTERNAL: 'خطأ داخلي',
    CONNECTION_FAILED: 'فشل الاتصال', PROVIDER_ERROR: 'فشل اختبار الاتصال',
  },
  templates: {
    // ----- الموافقات ------------------------------------------------------------------------------------------------------
    'approval.pending': { title: '{{item}} بانتظار موافقتك', body: ['{{details}}', '{{level}}'], subject: 'مطلوب موافقتك: {{item}}', cta: 'مراجعة الطلب' },
    'approval.pending#reassigned': { title: 'أُسند إليك: {{item}}', subject: 'أُسند إليك: {{item}}' },
    'approval.reminder': { title: 'تذكير: {{item}} بانتظار موافقتك', body: ['معلّق منذ {{waitingFor}}', '{{details}}'], bodyFallback: 'ما زال الطلب بانتظار قرارك.', subject: 'تذكير: {{item}} بانتظار موافقتك', cta: 'مراجعة الطلب' },
    'approval.reminder#reminder': {},
    'approval.reminder#digest': { title: 'بانتظارك: {{approvalsCount}}', body: ['{{countsList}}'], bodyFallback: 'ملخصك اليومي للطلبات التي تنتظر قرارك.', subject: 'ملخص الموافقات: {{approvalsCount}} بانتظارك', cta: 'فتح الموافقات' },
    'approval.escalated': { title: 'صُعِّد إليك: {{item}}', body: ['لم يُتخذ قرار في {{level}} في الوقت المحدد وأصبح بانتظارك أيضًا', '{{details}}'], subject: 'صُعِّد إليك: {{item}}', cta: 'مراجعة الطلب' },
    'approval.decided': { title: 'صدر قرار بشأن: {{item}}', body: ['تعليق: {{comment}}', '{{details}}'], bodyFallback: 'افتح الطلب لمعرفة من اتخذ القرار ومتى.', cta: 'عرض الطلب' },
    'approval.decided#APPROVED': { title: 'تمت الموافقة: {{item}}', subject: 'تمت الموافقة: {{item}}' },
    'approval.decided#REJECTED': { title: 'تم الرفض: {{item}}', subject: 'تم الرفض: {{item}}' },
    'approval.decided#CANCELLED': { title: 'تم السحب: {{item}}', body: ['السبب: {{comment}}', '{{details}}'], subject: 'تم السحب: {{item}}' },
    'approval.decided#INVALIDATED': { title: 'تغيّر الطلب أثناء انتظار القرار ويحتاج إلى قرار جديد: {{item}}', body: ['السبب: {{comment}}', '{{details}}'], subject: 'تغيّر أثناء الانتظار: {{item}}' },
    'approval.info_requested': { title: 'مطلوب مزيد من المعلومات: {{item}}', body: ['السؤال: {{comment}}', '{{details}}'], bodyFallback: 'طلب أحد المعتمدين مزيدًا من المعلومات قبل اتخاذ القرار.', subject: 'سؤال بشأن: {{item}}', cta: 'الإجابة عن السؤال' },
    'approval.info_answered': { title: 'وصلت الإجابة: {{item}}', body: ['الإجابة: {{comment}}', '{{details}}'], bodyFallback: 'أجاب مقدّم الطلب عن سؤالك، والطلب بانتظار قرارك.', cta: 'مراجعة الطلب' },
    'approval.reassigned': { title: 'أُعيد إسناد الطلب: {{item}}', body: ['السبب: {{reason}}'], bodyFallback: 'لم يعد الطلب بانتظارك.', cta: 'عرض الطلب' },
    'approval.bypassed': { title: 'تمت الموافقة استثناءً: {{item}}', body: ['لا يلزم أي إجراء منك', 'السبب: {{reason}}'], subject: 'موافقة استثنائية: {{item}}', cta: 'عرض الطلب' },

    // ----- الحضور ---------------------------------------------------------------------------------------------------------
    'attendance.unexcused_marked': { title: 'أيام حضور غير مبرّرة: {{daysCount}}', body: ['{{dateList}}', '{{autoDeductNote}}'], bodyFallback: 'لم يُقدَّم سبب خلال فترة السماح.', cta: 'عرض الحضور' },
    'attendance.unexcused_marked#self': { title: 'أيام حضورك غير المبرّرة: {{daysCount}}', body: ['{{dateList}}', '{{autoDeductNote}}', 'أضف سببًا لكل يوم ليراجعه مديرك'], cta: 'مراجعة حضوري' },
    'attendance.unexcused_marked#manager': { title: '{{employeeName|أحد الموظفين}}: أيام غير مبرّرة: {{daysCount}}', cta: 'فتح سجل الحضور' },
    'attendance.note_submitted': { title: 'سبب حضور من {{employeeName|أحد الموظفين}}', body: ['عن يوم {{attendanceDate}}'], bodyFallback: 'قُدّم سبب عن أحد الأيام.', cta: 'عرض السبب' },
    'attendance.note_decided': { title: 'روجع سببك عن يوم {{attendanceDate|أحد الأيام}}', body: ['{{reason}}'], bodyFallback: 'افتح طلباتك لمعرفة القرار.', cta: 'عرض طلباتي' },
    'attendance.note_decided#approved': { title: 'قُبل سببك عن يوم {{attendanceDate|أحد الأيام}}', body: ['تعليق: {{reason}}'], bodyFallback: 'أصبح اليوم مبرّرًا ولم يُخصم شيء.' },
    'attendance.note_decided#excused': { title: 'أُعفي يوم {{attendanceDate|أحد الأيام}}', body: ['تعليق: {{reason}}'], bodyFallback: 'أُعفي اليوم ولم يُخصم شيء.' },
    'attendance.note_decided#rejected': { title: 'لم يُقبل سببك عن يوم {{attendanceDate|أحد الأيام}}', body: ['السبب: {{reason}}'], bodyFallback: 'لم يُطبَّق أي أثر على الراتب.' },
    'attendance.note_decided#rejected_leave': { title: 'لم يُقبل سببك عن يوم {{attendanceDate|أحد الأيام}}', body: ['خُصم {{payEffect}} من رصيد {{leaveTypeLabel}}', 'السبب: {{reason}}'], bodyFallback: 'خُصم اليوم من رصيد الإجازة المدفوعة.' },
    'attendance.note_decided#rejected_lop': { title: 'لم يُقبل سببك عن يوم {{attendanceDate|أحد الأيام}}', body: ['سُجّل {{payEffect}} بدون أجر', 'السبب: {{reason}}'], bodyFallback: 'سُجّل اليوم بدون أجر.' },
    'attendance.note_info_requested': { title: 'سؤال عن سببك ليوم {{attendanceDate|أحد الأيام}}', body: ['{{question}}'], bodyFallback: 'طلب مديرك مزيدًا من المعلومات.', cta: 'الإجابة عن السؤال' },
    'attendance.selfie_submitted': { title: 'تسجيل حضور بصورة ذاتية من {{employeeName|أحد الموظفين}}', body: ['{{at}}'], bodyFallback: 'بانتظار مراجعتك.', cta: 'مراجعة الصورة الذاتية' },
    'attendance.selfie_submitted#in': {},
    'attendance.selfie_submitted#out': { title: 'تسجيل انصراف بصورة ذاتية من {{employeeName|أحد الموظفين}}' },
    'attendance.selfie_decided': { title: 'روجع {{selfieKind}} بالصورة الذاتية', body: ['{{at}}', '{{reason}}'], bodyFallback: 'افتح طلباتك للتفاصيل.', cta: 'عرض طلباتي' },
    'attendance.selfie_decided#approved': { title: 'تمت الموافقة على {{selfieKind}} بالصورة الذاتية', body: ['{{at}}', 'تعليق: {{reason}}'], bodyFallback: 'سُجّلت البصمة.' },
    'attendance.selfie_decided#rejected': { title: 'لم تتم الموافقة على {{selfieKind}} بالصورة الذاتية', body: ['{{at}}', 'السبب: {{reason}}'], bodyFallback: 'لم تُسجَّل البصمة.' },
    'attendance.punch_flagged': { title: '{{punchKind}} بحاجة إلى مراجعة: {{employeeName|أحد الموظفين}}', body: ['{{reasonText}}', '{{geofenceName}}', 'المسافة: {{distance}}', '{{at}}'], bodyFallback: 'افتح سجل الحضور للتفاصيل.', cta: 'عرض الحضور' },
    'attendance.punch_flagged#denied': { title: 'رُفض {{punchKind}}: {{employeeName|أحد الموظفين}}' },
    'attendance.punch_flagged#flagged': {},
    'attendance.regularisation_decided': { title: 'روجعت تسوية يوم {{attendanceDate|أحد الأيام}}', body: ['{{regularisationType}}', '{{comment}}'], bodyFallback: 'افتح طلباتك للتفاصيل.', cta: 'عرض طلباتي' },
    'attendance.regularisation_decided#approved': { title: 'تمت الموافقة على تسوية يوم {{attendanceDate|أحد الأيام}}', body: ['{{regularisationType}}', 'تعليق: {{comment}}'], bodyFallback: 'طُبّقت البصمات المصحّحة.' },
    'attendance.regularisation_decided#rejected': { title: 'لم تتم الموافقة على تسوية يوم {{attendanceDate|أحد الأيام}}', body: ['{{regularisationType}}', 'السبب: {{comment}}'], bodyFallback: 'يبقى اليوم كما سُجّل.' },
    'punch.missing_out': { title: 'لم تسجّل انصرافك بعد ({{attendanceDate|اليوم}})', body: ['سجّلت حضورك الساعة {{firstInTime}}', 'انتهى يوم عملك الساعة {{endTime}}', 'سجّل انصرافك الآن، أو اطلب تصحيحًا إن كنت قد غادرت'], subject: 'تذكير: سجّل انصرافك ({{attendanceDate|اليوم}})', cta: 'تسجيل الانصراف' },
    'punch.missing_out#shift': { body: ['سجّلت حضورك الساعة {{firstInTime}}', 'انتهت مناوبتك الساعة {{endTime}}', 'سجّل انصرافك الآن، أو اطلب تصحيحًا إن كنت قد غادرت'] },
    'punch.missing_out#default': {},
    'shift.swap_requested': { title: 'طلب {{requesterName|أحد الزملاء}} تبديل المناوبة معك', body: ['{{swapDate}}', '{{requesterShiftName}} ⇄ {{targetShiftName}}'], bodyFallback: 'يقرّر مديرك طلب التبديل.', cta: 'عرض مناوبتي' },
    'shift.swap_decided': { title: 'روجع تبديل المناوبة يوم {{swapDate|اليوم المطلوب}}', body: ['{{comment}}'], bodyFallback: 'افتح مناوبتك للتفاصيل.', cta: 'عرض مناوبتي' },
    'shift.swap_decided#approved': { title: 'تمت الموافقة على تبديل المناوبة يوم {{swapDate|اليوم المطلوب}}', body: ['تعليق: {{comment}}'], bodyFallback: 'تغيّرت مناوبتك في ذلك اليوم.' },
    'shift.swap_decided#rejected': { title: 'لم تتم الموافقة على تبديل المناوبة يوم {{swapDate|اليوم المطلوب}}', body: ['السبب: {{comment}}'], bodyFallback: 'تبقى المناوبات كما هي.' },

    // ----- الإجازات -------------------------------------------------------------------------------------------------------
    'leave.requested': { title: 'طلب إجازة من {{employeeName|أحد الموظفين}}', body: ['{{leaveTypeName}}', '{{range}}'], bodyFallback: 'بانتظار القرار.', cta: 'مراجعة طلبات الإجازة' },
    'leave.approved': { title: 'تمت الموافقة على الإجازة: {{leaveTypeName|إجازتك}}', body: ['{{range}}', 'ملاحظة: {{decisionNote}}'], bodyFallback: 'تمت الموافقة على طلب إجازتك.', subject: 'تمت الموافقة على إجازتك', cta: 'عرض إجازاتي' },
    'leave.rejected': { title: 'لم تتم الموافقة على الإجازة: {{leaveTypeName|إجازتك}}', body: ['{{range}}', 'السبب: {{decisionNote}}'], bodyFallback: 'لم تتم الموافقة على طلب إجازتك.', subject: 'لم تتم الموافقة على إجازتك', cta: 'عرض إجازاتي' },
    'leave.info_requested': { title: 'سؤال عن طلب إجازتك', body: ['{{question}}', '{{leaveTypeName}}', '{{range}}'], bodyFallback: 'طلب أحد المعتمدين مزيدًا من المعلومات.', cta: 'الإجابة عن السؤال' },
    'leave.comment_added': { title: 'تعليق جديد على طلب إجازة {{employeeName|أحد الموظفين}}', body: ['{{excerpt}}', '{{leaveTypeName}}'], bodyFallback: 'افتح المحادثة لقراءة التعليق.', cta: 'عرض الطلب' },
    'leave.comment_added#employee': { title: 'تعليق جديد على طلب إجازتك', cta: 'عرض إجازاتي' },
    'leave.comment_added#approvers': {},
    'leave.year_closed': { title: 'أُغلقت سنة الإجازات {{fromYear}}', body: ['الأرصدة المرحّلة إلى {{toYear}}: {{balancesCarried}}', 'الإجمالي: {{totalDaysPhrase}}'], bodyFallback: 'اكتمل الترحيل.', cta: 'عرض الأرصدة' },
    'leave.comp_off_expired': { title: 'انتهت صلاحية رصيد إجازة تعويضية', body: ['رصيد غير مستخدم: {{compOffDays}}، انتهى في {{expiredOn}}'], bodyFallback: 'انتهت صلاحية رصيد تعويضي غير مستخدم.', cta: 'عرض إجازاتي' },

    // ----- التقارير -------------------------------------------------------------------------------------------------------
    'report.ready': { title: 'التقرير جاهز: {{reportName}}', body: ['تقريرك جاهز — افتحه لعرضه أو تنزيله.'], cta: 'عرض التقرير' },
    'report.failed': { title: 'تعذّر إنشاء التقرير: {{reportName}}', body: ['{{error}}'], bodyFallback: 'تعذّر إنشاء التقرير. حاول مرة أخرى أو تواصل مع الدعم.', cta: 'فتح التقارير' },
    'report.scheduled_delivery': { title: 'تقرير لك: {{reportName}}', body: ['{{period}}', '{{scheduleName}}'], bodyFallback: 'افتحه لعرضه أو تنزيله.', cta: 'عرض التقرير' },
    'report.scheduled_delivery#send_now': { title: 'تمت مشاركة تقرير معك: {{reportName}}' },
    'report.scheduled_delivery#scheduled': { title: 'تقرير مجدول: {{reportName}}' },

    // ----- الأجهزة والمزامنة والنظام ---------------------------------------------------------------------------------------
    'device.offline': { title: 'الجهاز غير متصل: {{deviceName|أحد الأجهزة}}', body: ['آخر اتصال: {{lastSeenAt}}'], bodyFallback: 'لا يوجد اتصال ناجح منذ فترة.', cta: 'فتح الجهاز' },
    'device.online': { title: 'عاد الجهاز للاتصال: {{deviceName|أحد الأجهزة}}', body: ['آخر اتصال: {{lastSeenAt}}'], bodyFallback: 'استؤنف الاتصال.', cta: 'فتح الجهاز' },
    'sync.failed': { title: 'فشلت المزامنة: {{jobTypeText}}', body: ['{{error}}'], bodyFallback: 'افتح مهمة المزامنة للتفاصيل.', cta: 'فتح مهمة المزامنة' },
    'sync.completed': { title: 'اكتملت المزامنة: {{jobTypeText}}', body: ['نجح: {{itemsSuccess}}', 'فشل: {{itemsFailed}}'], bodyFallback: 'انتهت مهمة المزامنة.', cta: 'فتح مهمة المزامنة' },
    'sync.finance.failed': { title: 'تتعثّر {{financeDirection}} مع Flowza Finance', body: ['محاولات فاشلة متتالية: {{consecutiveFailures}}', '{{codeText}}: {{error}}'], bodyFallback: 'راجع الربط من الإعدادات ← التكاملات.', cta: 'فتح التكاملات' },
    'sync.finance.failed#streak': {},
    'sync.finance.failed#batch_skipped': { title: 'تخطّى الإرسال إلى Flowza Finance بصمات تعذّر حفظها', body: ['البصمات المتخطّاة: {{punchesPhrase}}', '{{codeText}}: {{error}}'] },
    'employee.imported': { title: 'استيراد الموظفين', body: ['المستوردون: {{imported}}', 'الصفوف الصالحة: {{validRows}}'], bodyFallback: 'افتح عملية الاستيراد للتفاصيل.', cta: 'فتح الاستيراد' },
    'employee.imported#queued': { title: 'بدأ استيراد الموظفين', body: ['الصفوف الصالحة: {{validRows}}'], bodyFallback: 'الاستيراد قيد التنفيذ.' },
    'employee.imported#finished': { title: 'اكتمل استيراد الموظفين', body: ['المستوردون: {{imported}}'], bodyFallback: 'اكتمل الاستيراد.' },
    'subscription.limit_reached': { title: 'تم بلوغ حد الخطة: {{metricText}}', body: ['الحد: {{limit}}'], bodyFallback: 'رقِّ الخطة أو حرّر سعة للمتابعة.', cta: 'فتح الاشتراك' },
  },
};
