import type { LocaleTemplates } from './types.js';

/** English notification templates (HR portal Prompt 8). Keys: notification type, or `type#variant` for outcome-specific texts. */
export const en: LocaleTemplates = {
  locale: 'en',
  dir: 'ltr',
  formats: { date: 'd MMM yyyy', dateTime: 'd MMM yyyy, HH:mm', time: 'HH:mm' },
  separators: { parts: ' · ', list: ', ', range: ' → ' },
  common: {
    brand: 'FlowZa Time',
    footer: 'You receive this e-mail because you are a member of {{org}} on FlowZa Time.',
    footerPreferences: 'Choose which e-mails you receive in your notification settings.',
    footerLocked: 'This notice cannot be switched off.',
    preferencesLink: 'Notification settings',
    linkFallback: 'If the button does not work, open this link:',
    approve: 'Approve',
    reject: 'Reject',
    oneClickHeading: 'Or decide from this e-mail:',
    oneClickNote: 'You will be asked to confirm in FlowZa Time before anything is recorded. Each link works once and expires in 7 days. If you did not expect this e-mail, ignore it.',
    level: 'Level {{stepNo}}',
    autoDeductNote: 'The pay effect was applied per the attendance policy',
    selfieKind: { in: 'check-in', out: 'check-out' },
    punchKind: { in: 'Check-in', out: 'Check-out' },
    financeDirection: { pull: 'pull', push: 'push', sync: 'sync' },
    payEffect: { half: 'Half a day', one: 'One day', other: '{{n}} days' },
  },
  plurals: {
    days: { one: '{{n}} day', other: '{{n}} days' },
    attendanceDays: { one: '{{n}} attendance day', other: '{{n}} attendance days' },
    hours: { one: '{{n}} hour', other: '{{n}} hours' },
    approvals: { one: '{{n}} approval', other: '{{n}} approvals' },
    balances: { one: '{{n}} balance', other: '{{n}} balances' },
    punches: { one: '{{n}} punch', other: '{{n}} punches' },
  },
  entities: {
    ATTENDANCE_CORRECTION: 'Attendance correction', LEAVE: 'Leave request', OVERTIME: 'Overtime', MISSING_PUNCH: 'Missing punch', SHIFT_CHANGE: 'Shift change',
    MANUAL_ATTENDANCE: 'Manual attendance', ATTENDANCE_NOTE: 'Attendance reason', SHIFT_SWAP: 'Shift swap', COMP_OFF: 'Comp-off', REGULARISATION: 'Regularisation', OVERTIME_CLAIM: 'Overtime claim',
  },
  reportTypes: {
    daily_attendance: 'Daily attendance', monthly_attendance: 'Monthly attendance', employee_attendance: 'Employee attendance', branch_attendance: 'Branch attendance',
    department_attendance: 'Department attendance', late_report: 'Late arrivals', absence_report: 'Absences', overtime_report: 'Overtime', missing_punch_report: 'Missing punches',
    device_sync_report: 'Device sync', device_health_report: 'Device health', audit_report: 'Audit', payroll_summary: 'Payroll summary', employee_directory: 'Employee directory',
    leave_report: 'Leave', attendance_summary: 'Attendance summary', weekly_attendance: 'Weekly attendance', weekly_in_out: 'Weekly in / out', monthly_summary: 'Monthly attendance summary', monthly_detail: 'Monthly attendance detail',
  },
  syncJobTypes: {
    PULL_ATTENDANCE: 'Attendance pull', PULL_EMPLOYEES: 'Employee pull', PUSH_EMPLOYEE: 'Employee push', PUSH_EMPLOYEES: 'Employee push', DEVICE_HEALTH_CHECK: 'Health check',
    RECONCILIATION: 'Reconciliation', TEST_CONNECTION: 'Connection test', DELETE_EMPLOYEE: 'Employee removal', RESTART_DEVICE: 'Device restart', PUSH_ATTENDANCE: 'Attendance push',
  },
  geofenceReasons: {
    outside: 'Outside the work zone', mock_location: 'Mock location detected', location_missing: 'No location shared', gps_accuracy_too_low: 'Location too imprecise',
    out_of_window: 'Outside the allowed hours', no_fences_assigned: 'No work zone assigned', geofence_off: 'Work zone checks off', inside: 'Inside the work zone',
  },
  regularisationTypes: { missed_punch: 'Missed punch', wrong_punch: 'Wrong punch', wfh_unmarked: 'Work from home not marked', system_downtime: 'System downtime' },
  metrics: { employees: 'Employees', devices: 'Devices', branches: 'Branches', users: 'Users', storage_mb: 'Storage', api_calls_month: 'API calls' },
  financeErrors: {
    AUTH_FAILED: 'Credential rejected', DEVICE_OFFLINE: 'Unreachable', RATE_LIMITED: 'Rate limited', TIMEOUT: 'Timed out', UNSUPPORTED: 'Not supported', NOT_FOUND: 'Not found',
    INVALID_CONFIG: 'Configuration problem', VENDOR_ERROR: 'Finance error', NOT_IMPLEMENTED: 'Not available', PROTOCOL_ERROR: 'Unreadable answer', CONFLICT: 'Conflict', INTERNAL: 'Internal error',
    CONNECTION_FAILED: 'Connection failed', PROVIDER_ERROR: 'Connection test failed',
  },
  templates: {
    // ----- approvals ------------------------------------------------------------------------------------------------------
    'approval.pending': { title: '{{item}} is waiting for your approval', body: ['{{details}}', '{{level}}'], subject: 'Approval needed: {{item}}', cta: 'Review the request' },
    'approval.pending#reassigned': { title: '{{item}} was reassigned to you', subject: 'Reassigned to you: {{item}}' },
    'approval.reminder': { title: 'Reminder: {{item}} is waiting for your approval', body: ['Pending for {{waitingFor}}', '{{details}}'], bodyFallback: 'The request is still waiting for your decision.', subject: 'Reminder: {{item}} is waiting for your approval', cta: 'Review the request' },
    'approval.reminder#reminder': {},
    'approval.reminder#digest': { title: '{{approvalsCount}} waiting for you', body: ['{{countsList}}'], bodyFallback: 'Your daily summary of the approvals waiting for your decision.', subject: 'Your approvals digest: {{approvalsCount}} waiting', cta: 'Open approvals' },
    'approval.escalated': { title: 'Escalated to you: {{item}}', body: ['{{level}} was not decided in time and now waits for you too', '{{details}}'], subject: 'Escalated to you: {{item}}', cta: 'Review the request' },
    'approval.decided': { title: '{{item}}: a decision was made', body: ['Comment: {{comment}}', '{{details}}'], bodyFallback: 'Open the request to see who decided and when.', cta: 'View the request' },
    'approval.decided#APPROVED': { title: '{{item}} was approved', subject: 'Approved: {{item}}' },
    'approval.decided#REJECTED': { title: '{{item}} was rejected', subject: 'Rejected: {{item}}' },
    'approval.decided#CANCELLED': { title: '{{item}} was withdrawn', body: ['Reason: {{comment}}', '{{details}}'], subject: 'Withdrawn: {{item}}' },
    'approval.decided#INVALIDATED': { title: '{{item}} changed while pending and needs a new decision', body: ['Reason: {{comment}}', '{{details}}'], subject: 'Changed while pending: {{item}}' },
    'approval.info_requested': { title: 'More information needed: {{item}}', body: ['Question: {{comment}}', '{{details}}'], bodyFallback: 'An approver asked for more information before deciding.', subject: 'Question about {{item}}', cta: 'Answer the question' },
    'approval.info_answered': { title: 'Answer received: {{item}}', body: ['Answer: {{comment}}', '{{details}}'], bodyFallback: 'The requester answered your question. The request is waiting for your decision.', cta: 'Review the request' },
    'approval.reassigned': { title: '{{item}} was reassigned', body: ['Reason: {{reason}}'], bodyFallback: 'The request no longer waits for you.', cta: 'View the request' },
    'approval.bypassed': { title: '{{item}} was approved as an exception', body: ['No action is needed from you', 'Reason: {{reason}}'], subject: 'Approved as an exception: {{item}}', cta: 'View the request' },

    // ----- attendance -----------------------------------------------------------------------------------------------------
    'attendance.unexcused_marked': { title: 'Unexcused attendance: {{daysCount}}', body: ['{{dateList}}', '{{autoDeductNote}}'], bodyFallback: 'No reason was given within the grace period.', cta: 'View attendance' },
    'attendance.unexcused_marked#self': { title: 'Your attendance: {{daysCount}} marked unexcused', body: ['{{dateList}}', '{{autoDeductNote}}', 'Add a reason for each day so that your manager can review it'], cta: 'Review my attendance' },
    'attendance.unexcused_marked#manager': { title: '{{employeeName|An employee}}: {{daysCount}} marked unexcused', cta: 'Open the attendance register' },
    'attendance.note_submitted': { title: 'Attendance reason from {{employeeName|an employee}}', body: ['For {{attendanceDate}}'], bodyFallback: 'A reason was given for a day.', cta: 'View the reason' },
    'attendance.note_decided': { title: 'Your reason for {{attendanceDate|a day}} was reviewed', body: ['{{reason}}'], bodyFallback: 'Open your requests to see the decision.', cta: 'View my requests' },
    'attendance.note_decided#approved': { title: 'Your reason for {{attendanceDate|a day}} was accepted', body: ['Comment: {{reason}}'], bodyFallback: 'The day is explained; nothing is deducted.' },
    'attendance.note_decided#excused': { title: '{{attendanceDate|The day}} was excused', body: ['Comment: {{reason}}'], bodyFallback: 'The day is excused; nothing is deducted.' },
    'attendance.note_decided#rejected': { title: 'Your reason for {{attendanceDate|a day}} was not accepted', body: ['Reason: {{reason}}'], bodyFallback: 'No pay effect was applied.' },
    'attendance.note_decided#rejected_leave': { title: 'Your reason for {{attendanceDate|a day}} was not accepted', body: ['{{payEffect}} deducted from your {{leaveTypeLabel}} balance', 'Reason: {{reason}}'], bodyFallback: 'Paid leave was deducted for the day.' },
    'attendance.note_decided#rejected_lop': { title: 'Your reason for {{attendanceDate|a day}} was not accepted', body: ['{{payEffect}} recorded as loss of pay', 'Reason: {{reason}}'], bodyFallback: 'The day was recorded as loss of pay.' },
    'attendance.note_info_requested': { title: 'Question about your reason for {{attendanceDate|a day}}', body: ['{{question}}'], bodyFallback: 'Your manager asked for more information.', cta: 'Answer the question' },
    'attendance.selfie_submitted': { title: 'Selfie check-in from {{employeeName|an employee}}', body: ['{{at}}'], bodyFallback: 'Waiting for your review.', cta: 'Review the selfie' },
    'attendance.selfie_submitted#in': {},
    'attendance.selfie_submitted#out': { title: 'Selfie check-out from {{employeeName|an employee}}' },
    'attendance.selfie_decided': { title: 'Your selfie {{selfieKind}} was reviewed', body: ['{{at}}', '{{reason}}'], bodyFallback: 'Open your requests for the details.', cta: 'View my requests' },
    'attendance.selfie_decided#approved': { title: 'Your selfie {{selfieKind}} was approved', body: ['{{at}}', 'Comment: {{reason}}'], bodyFallback: 'The punch is recorded.' },
    'attendance.selfie_decided#rejected': { title: 'Your selfie {{selfieKind}} was not approved', body: ['{{at}}', 'Reason: {{reason}}'], bodyFallback: 'The punch was not recorded.' },
    'attendance.punch_flagged': { title: '{{punchKind}} flagged: {{employeeName|an employee}}', body: ['{{reasonText}}', '{{geofenceName}}', '{{distance}} away', '{{at}}'], bodyFallback: 'Open the attendance register for the details.', cta: 'View attendance' },
    'attendance.punch_flagged#denied': { title: '{{punchKind}} refused: {{employeeName|an employee}}' },
    'attendance.punch_flagged#flagged': {},
    'attendance.regularisation_decided': { title: 'Regularisation for {{attendanceDate|a day}} reviewed', body: ['{{regularisationType}}', '{{comment}}'], bodyFallback: 'Open your requests for the details.', cta: 'View my requests' },
    'attendance.regularisation_decided#approved': { title: 'Regularisation for {{attendanceDate|a day}} approved', body: ['{{regularisationType}}', 'Comment: {{comment}}'], bodyFallback: 'The corrected punches are applied.' },
    'attendance.regularisation_decided#rejected': { title: 'Regularisation for {{attendanceDate|a day}} not approved', body: ['{{regularisationType}}', 'Reason: {{comment}}'], bodyFallback: 'The day stays as it was recorded.' },
    'punch.missing_out': { title: 'You have not checked out yet ({{attendanceDate|today}})', body: ['You checked in at {{firstInTime}}', 'Your working day ended at {{endTime}}', 'Check out now, or ask for a correction if you have already left'], subject: 'Reminder: check out ({{attendanceDate|today}})', cta: 'Check out' },
    'punch.missing_out#shift': { body: ['You checked in at {{firstInTime}}', 'Your shift ended at {{endTime}}', 'Check out now, or ask for a correction if you have already left'] },
    'punch.missing_out#default': {},
    'shift.swap_requested': { title: '{{requesterName|A colleague}} asked to swap shifts with you', body: ['{{swapDate}}', '{{requesterShiftName}} ⇄ {{targetShiftName}}'], bodyFallback: 'Your manager decides the swap.', cta: 'View my shift' },
    'shift.swap_decided': { title: 'Shift swap on {{swapDate|the requested day}} reviewed', body: ['{{comment}}'], bodyFallback: 'Open your shift for the details.', cta: 'View my shift' },
    'shift.swap_decided#approved': { title: 'Shift swap on {{swapDate|the requested day}} approved', body: ['Comment: {{comment}}'], bodyFallback: 'Your shift for that day has changed.' },
    'shift.swap_decided#rejected': { title: 'Shift swap on {{swapDate|the requested day}} not approved', body: ['Reason: {{comment}}'], bodyFallback: 'Your shifts stay as they were.' },

    // ----- leave ----------------------------------------------------------------------------------------------------------
    'leave.requested': { title: 'Leave request from {{employeeName|an employee}}', body: ['{{leaveTypeName}}', '{{range}}'], bodyFallback: 'Waiting for a decision.', cta: 'Review leave requests' },
    'leave.approved': { title: 'Leave approved: {{leaveTypeName|your leave}}', body: ['{{range}}', 'Note: {{decisionNote}}'], bodyFallback: 'Your leave request was approved.', subject: 'Your leave was approved', cta: 'View my leave' },
    'leave.rejected': { title: 'Leave not approved: {{leaveTypeName|your leave}}', body: ['{{range}}', 'Reason: {{decisionNote}}'], bodyFallback: 'Your leave request was not approved.', subject: 'Your leave was not approved', cta: 'View my leave' },
    'leave.info_requested': { title: 'Question about your leave request', body: ['{{question}}', '{{leaveTypeName}}', '{{range}}'], bodyFallback: 'An approver asked for more information.', cta: 'Answer the question' },
    'leave.comment_added': { title: 'New comment on the leave request of {{employeeName|an employee}}', body: ['{{excerpt}}', '{{leaveTypeName}}'], bodyFallback: 'Open the conversation to read it.', cta: 'View the request' },
    'leave.comment_added#employee': { title: 'New comment on your leave request', cta: 'View my leave' },
    'leave.comment_added#approvers': {},
    'leave.year_closed': { title: 'Leave year {{fromYear}} closed', body: ['{{balancesCarried}} carried into {{toYear}}', 'Total: {{totalDaysPhrase}}'], bodyFallback: 'The carry-forward is complete.', cta: 'View allocations' },
    'leave.comp_off_expired': { title: 'Comp-off credit expired', body: ['{{compOffDays}} unused, expired on {{expiredOn}}'], bodyFallback: 'An unused comp-off credit expired.', cta: 'View my leave' },

    // ----- reports --------------------------------------------------------------------------------------------------------
    'report.ready': { title: 'Report ready: {{reportName}}', body: ['Your report is ready — open it to view or download it.'], cta: 'View the report' },
    'report.failed': { title: 'Report failed: {{reportName}}', body: ['{{error}}'], bodyFallback: 'The report could not be generated. Try again or contact support.', cta: 'Open reports' },
    'report.scheduled_delivery': { title: 'Report for you: {{reportName}}', body: ['{{period}}', '{{scheduleName}}'], bodyFallback: 'Open it to view or download it.', cta: 'View the report' },
    'report.scheduled_delivery#send_now': { title: 'Report shared with you: {{reportName}}' },
    'report.scheduled_delivery#scheduled': { title: 'Scheduled report: {{reportName}}' },

    // ----- devices, sync, system ------------------------------------------------------------------------------------------
    'device.offline': { title: 'Device offline: {{deviceName|a device}}', body: ['Last contact {{lastSeenAt}}'], bodyFallback: 'No successful communication for a while.', cta: 'Open the device' },
    'device.online': { title: 'Device back online: {{deviceName|a device}}', body: ['Last contact {{lastSeenAt}}'], bodyFallback: 'Communication has resumed.', cta: 'Open the device' },
    'sync.failed': { title: 'Sync failed: {{jobTypeText}}', body: ['{{error}}'], bodyFallback: 'Open the sync job for the details.', cta: 'Open the sync job' },
    'sync.completed': { title: 'Sync completed: {{jobTypeText}}', body: ['Succeeded: {{itemsSuccess}}', 'Failed: {{itemsFailed}}'], bodyFallback: 'The sync job finished.', cta: 'Open the sync job' },
    'sync.finance.failed': { title: 'Flowza Finance {{financeDirection}} is failing', body: ['Consecutive failures: {{consecutiveFailures}}', '{{codeText}}: {{error}}'], bodyFallback: 'Check the connector in Settings → Integrations.', cta: 'Open integrations' },
    'sync.finance.failed#streak': {},
    'sync.finance.failed#batch_skipped': { title: 'Flowza Finance push skipped punches it could not store', body: ['Skipped: {{punchesPhrase}}', '{{codeText}}: {{error}}'] },
    'employee.imported': { title: 'Employee import', body: ['Imported: {{imported}}', 'Valid rows: {{validRows}}'], bodyFallback: 'Open the import for the details.', cta: 'Open the import' },
    'employee.imported#queued': { title: 'Employee import started', body: ['Valid rows: {{validRows}}'], bodyFallback: 'The import is running.' },
    'employee.imported#finished': { title: 'Employee import finished', body: ['Imported: {{imported}}'], bodyFallback: 'The import is complete.' },
    'subscription.limit_reached': { title: 'Plan limit reached: {{metricText}}', body: ['Limit: {{limit}}'], bodyFallback: 'Upgrade the plan or free capacity to continue.', cta: 'Open subscription' },
  },
};
